image: docker:18

stages:
  - build

services:
  - docker:18-dind
  
variables:
  SERVER_IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  SERVER_RELEASE_TAG: $CI_REGISTRY_IMAGE:latest
  CONSUMER_IMAGE_TAG: $CI_REGISTRY_IMAGE/consumer:$CI_COMMIT_REF_SLUG
  CONSUMER_RELEASE_TAG: $CI_REGISTRY_IMAGE/consumer:latest

before_script:
  - docker info
  - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD


build_auto_server:
  stage: build
  script:
    - docker build -t ${SERVER_RELEASE_TAG} -f Dockerfile.server .
    - docker push ${SERVER_RELEASE_TAG}
  only:
    refs:
      - master

build_auto_consumer:
  stage: build
  script:
    - docker build -t ${CONSUMER_RELEASE_TAG} -f Dockerfile.consumer .
    - docker push ${CONSUMER_RELEASE_TAG}
  only:
    refs:
      - master

build_auto_develop_server:
  stage: build
  script:
    - docker build -t ${SERVER_IMAGE_TAG} -f Dockerfile.server .
    - docker push ${SERVER_IMAGE_TAG}
  only:
    refs:
      - develop

build_auto_develop_consumer:
  stage: build
  script:
    - docker build -t ${CONSUMER_IMAGE_TAG} -f Dockerfile.consumer .
    - docker push ${CONSUMER_IMAGE_TAG}
  only:
    refs:
      - develop


build_adhoc_server_master:
  stage: build
  script:
    - docker build -t ${SERVER_RELEASE_TAG} -f Dockerfile.server .
    - docker push ${SERVER_RELEASE_TAG}
  only:
    refs:
      - master
  when: manual


build_adhoc_server_non_master:
  stage: build
  script:
    - docker build -t ${SERVER_IMAGE_TAG} -f Dockerfile.server .
    - docker push ${SERVER_IMAGE_TAG}
  except:
    refs:
      - master
  when: manual

build_adhoc_consumer_master:
  stage: build
  script:
    - docker build -t ${CONSUMER_RELEASE_TAG} -f Dockerfile.consumer .
    - docker push ${CONSUMER_RELEASE_TAG}
  only:
    refs:
      - master
  when: manual


build_adhoc_consumer_non_master:
  stage: build
  script:
    - docker build -t ${CONSUMER_IMAGE_TAG} -f Dockerfile.consumer .
    - docker push ${CONSUMER_IMAGE_TAG}
  except:
    refs:
      - master
  when: manual


