image: docker:18

stages:
  - build

services:
  - docker:18-dind
  
variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

before_script:
  - docker info
  - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD


build_auto_server:
  stage: build
  script:
    - docker build -t ${CONTAINER_RELEASE_IMAGE} -f Dockerfile.server .
    - docker push ${CONTAINER_RELEASE_IMAGE}
  only:
    refs:
      - master

build_auto_develop_server:
  stage: build
  script:
    - docker build -t ${IMAGE_TAG} -f Dockerfile.server .
    - docker push ${IMAGE_TAG}
  only:
    refs:
      - develop


build_adhoc_server_master:
  stage: build
  script:
    - docker build -t ${CONTAINER_RELEASE_IMAGE} -f Dockerfile.server .
    - docker push ${CONTAINER_RELEASE_IMAGE}
  only:
    refs:
      - master
  when: manual


build_adhoc_server_non_master:
  stage: build
  script:
    - docker build -t ${IMAGE_TAG} -f Dockerfile.server .
    - docker push ${IMAGE_TAG}
  except:
    refs:
      - master
  when: manual


