FROM python:3.8 as builder

RUN apt update
RUN apt install -y cmake make git openssh-client gcc g++ musl-dev libmariadb-dev libffi-dev rustc cargo flex bison
RUN apt clean
# force using bash shell
SHELL ["/bin/bash", "-c"]

# pass through environment variables
ENV VENV=/venv
ENV PATH="$VENV/bin:$PATH"

RUN python -m venv $VENV

# ensure pip is upto date
RUN pip install --no-cache-dir --upgrade pip setuptools

# setup pip
RUN pip config --site set global.no-cache-dir false

# install wheel
RUN pip install wheel

# install the consumer
WORKDIR /checkouts
COPY . .
RUN pip --no-cache-dir install .

FROM python:3.8-slim

RUN apt update
RUN apt install -y bash libmariadb-dev
RUN apt clean

# force using bash shell
SHELL ["/bin/bash", "-c"]

ENV VENV=/venv
ENV PATH="$VENV/bin:$PATH"

COPY --from=builder $VENV $VENV

CMD python -m wwpdb.apps.content_ws_server.service.ContentRequestServiceHandler --start && tail -f /dev/null


