FROM python:3.8 as builder

RUN apt-get update
RUN apt-get install -y cmake make git openssh-client gcc g++ musl-dev libmariadb-dev libffi-dev rustc cargo flex bison
RUN apt-get clean

# force using bash shell
SHELL ["/bin/bash", "-c"]

# useful environment variables
ENV VENV=/venv
ENV PATH="$VENV/bin:$PATH"

RUN python -m venv $VENV

# ensure pip is upto date
RUN pip install --no-cache-dir --upgrade pip setuptools

# setup pip
RUN pip config --site set global.no-cache-dir false

# install wheel
RUN pip install wheel

# install the server
WORKDIR /checkouts
COPY . .
RUN pip --no-cache-dir install .[server]

# install gunicorn for serving the wsgi scripts
RUN pip install gunicorn

FROM python:3.8-slim

RUN apt-get update
RUN apt-get install -y bash
RUN apt-get clean

# force using bash shell
SHELL ["/bin/bash", "-c"]

ENV VENV=/venv
ENV PATH="$VENV/bin:$PATH"

COPY --from=builder $VENV $VENV

CMD gunicorn wwpdb.apps.content_ws_server.webapp.wsgi --bind 0.0.0.0:8080 --timeout 0 --threads 4


